name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        # MYSQL_DATABASE - name for the default database that is created
        mysql database: ragnarok
        # MYSQL_USER - create the specified user with superuser power for created database
        mysql user: ragnarok
        # MYSQL_PASSWORD - specified superuser password which user is power for created database
        mysql password: ragnarok
    - name: Create Database
      run: |
        sudo systemctl start mysql
        mysql -uroot -e "SHOW DATABASES"
        mysql -u root ragnarok < sql-files/main.sql || aborterror "Unable to import main database."
        mysql -u root ragnarok < sql-files/logs.sql || aborterror "Unable to import logs database."
        mysql -u root ragnarok < sql-files/custom.sql || aborterror "Unable to import logs database."
    - uses: actions/checkout@v2
    - name: Configure Files
      run: ./configure --enable-prere=no --enable-vip=yes --enable-buildbot=yes
    - name: Compile Server
      run: make server
    - name: Run Login
      run: ./login-server --run-once
