name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
        
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup MySQL
      run: |
        sudo systemctl enable mysql.service
        sudo systemctl start mysql.service
        mysql -u root -proot -e "CREATE DATABASE ragnarok;"
        mysql -u root -proot ragnarok < sql-files/main.sql
    - name: Configure Files
      run: ./configure --enable-prere=no --enable-vip=yes --enable-buildbot=yes
    - name: Compile Server
      run: make server
    - name: Run Login
      run: ./login-server --run-once
